version: '3.4'

services:
  productauditsystem.api:
    image: ${DOCKER_REGISTRY-}productauditsystemapi
    build:
      context: .
      dockerfile: ProductAuditSystem.API/Dockerfile

  productauditsystem-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ProductAuditSystem.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "P4ssw0rd!"

